# Generated by Django 4.2.2 on 2023-07-22 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_todolistmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistmodel',
            name='task_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='task_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='task_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='user_en',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='user_ru',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todolistmodel',
            name='user_uz',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
