# Generated by Django 4.2.2 on 2023-07-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_todolistmodel_task_en_todolistmodel_task_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistmodel',
            name='user_en',
        ),
        migrations.RemoveField(
            model_name='todolistmodel',
            name='user_ru',
        ),
        migrations.RemoveField(
            model_name='todolistmodel',
            name='user_uz',
        ),
    ]
